# Python First Project

In [2]:
import numpy as np

In [6]:
array1 = np.array([1, 2, 3, 4, 5])
array1[1:]

array([2, 3, 4, 5])

In [9]:
Nel_Array = np.array([[1, 2, 3, 4, 5],[23,10,15,16,20]])
Nel_Array[1,0:3]

array([23, 10, 15])

In [11]:
Name = np.eye(2)
Name

array([[1., 0.],
       [0., 1.]])

In [14]:
hey = np.zeros((3,3))
hey

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])